export const CLIENT_IDENTITY_REPOSITORY = Symbol('CLIENT_IDENTITY_REPOSITORY');
export const CLIENT_DOCUMENTS_REPOSITORY = Symbol('CLIENT_DOCUMENTS_REPOSITORY');
export const CLIENT_SUPPORT_REPOSITORY = Symbol('CLIENT_SUPPORT_REPOSITORY');
export const CLIENT_PREFERENCES_REPOSITORY = Symbol('CLIENT_PREFERENCES_REPOSITORY');
export const CLIENT_ORDERS_REPOSITORY = Symbol('CLIENT_ORDERS_REPOSITORY');
export const CLIENT_PROFILE_REPOSITORY = Symbol('CLIENT_PROFILE_REPOSITORY');
