export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const ROLES_REPOSITORY = Symbol('ROLES_REPOSITORY');
export const PERMISSIONS_REPOSITORY = Symbol('PERMISSIONS_REPOSITORY');
export const SESSIONS_REPOSITORY = Symbol('SESSIONS_REPOSITORY');
